title: Microsoft365.com/setup | Setup Office 365 Account | Download and Activate Office365
description: Visit microsoft365.com/setup and download office 365. Setup office 365 using the steps given here. Create an office365 account and get started with it.
